interface Services {
  id: number;
  imgSrc: string;
  name: string;
  description: string;
  timeslot: string;
}

const servicesCard: Services[] = [
  {
    id: 1,
    imgSrc: "images/service/service-1.jpg",
    name: "Full Body Massage",
    timeslot: "60 - 70 Minute Sessions",
    description:
      "At Santharpana Spa, we offer a range of rejuvenating massages to help you relax and unwind.Our full-body massage is designed to relieve stress and tension in the muscles, leaving you feeling refreshed and revitalized. This massage is perfect for those who want to pamper themselves after a long day or week.\n\n Our full-body massage lasts for 60 minutes and is performed by our experienced male therapists who have undergone extensive training in the art of massage. Our male therapists are known for their exceptional skill in providing deep relaxation to our guests. They are trained to identify the areas of the body that need extra attention and can customize the massage according to your needs.\n\n We use only the finest herbal oil or Aloe Vera cream for our full-body massage. Our herbal oil is made from natural ingredients and is free from any harmful chemicals. It helps to nourish the skin and improve blood circulation, providing a holistic experience. The Aloe Vera cream is perfect for those with sensitive skin as it is gentle and soothing. It helps to calm the mind and promote relaxation.\n\n During your massage, you will be treated to a full-body massage that includes your back, neck, shoulders, arms, legs, and feet. Our therapists use a combination of Swedish and deep tissue massage techniques to provide a relaxing and therapeutic experience. The massage helps to release tension in the muscles and improve flexibility, leaving you feeling lighter and more energized.\n\n At Santharpana Spa, we pride ourselves on our commitment to providing a luxurious and relaxing experience for our guests. Our full-body massage is priced at an affordable range, making it accessible to everyone. Our male therapists are trained to provide a professional and discreet service, ensuring your comfort and privacy throughout your visit.\n\n Book your full-body massage today and experience the ultimate in relaxation and rejuvenation at Santharpana Spa.",
  },
  {
    id: 2,
    imgSrc: "images/service/service-2.jpg",
    name: "Foot Massage",
    timeslot: "40 - 50 Minute Sessions",
    description:
      "At Santharpana Spa, we offer a rejuvenating foot massage that is designed to soothe tired feet and improve overall wellness. Our foot massage is a 40-50 minute session that is performed by our experienced therapists who have undergone extensive training in the art of massage.\n\n Our foot massage is a holistic treatment that focuses on the reflex points in the feet that correspond to different parts of the body. The massage technique involves applying pressure to these reflex points, which helps to stimulate blood circulation, reduce stress, and promote relaxation. \n\n During your foot massage, you will be seated in a comfortable chair as our therapists work their magic on your feet. Our therapists use a combination of massage techniques, including Swedish massage and Shiatsu, to provide a relaxing and therapeutic experience.\n\n Our foot massage is perfect for those who spend a lot of time on their feet, as it helps to relieve soreness and pain in the feet and legs. It is also ideal for those who suffer from conditions such as plantar fasciitis or arthritis, as the massage can help to reduce inflammation and improve flexibility.\n\n In addition to the physical benefits, our foot massage also has several mental and emotional benefits. It helps to reduce stress and anxiety levels, improve sleep quality, and promote a sense of well-being. \n\n At Santharpana Spa, we use only the finest natural oils and lotions for our foot massage. Our oils and lotions are made from natural ingredients and are free from any harmful chemicals. They help to nourish the skin and improve blood circulation, providing a holistic experience.\n\n Our foot massage is priced at an affordable rate, making it accessible to everyone. It is a popular treatment that is suitable for individuals of all ages and can be enjoyed on its own or as part of a larger spa package. \n\n Book your foot massage today and experience the ultimate in relaxation and rejuvenation at Santharpana Spa. Our experienced therapists will ensure that you receive a personalized and luxurious foot massage experience that will leave you feeling refreshed and revitalized.",
  },
  {
    id: 3,
    imgSrc: "images/service/service-4.jpg",
    name: "Sauna/Steam bath",
    timeslot: "10 - 20 Minute Sessions",
    description:
      "At Santharpana Spa, we offer a traditional steam bath experience that is designed to cleanse and rejuvenate your body. Our steam bath includes a unique blend of lime leaves, pawatta leaves, Justicia Adhatoda leaves, Kohoba leaves, and cinnamon leaves, which are known for their therapeutic properties. \n\n Our traditional steam bath is priced at an affordable range, making it accessible to everyone. The steam bath is a popular practice that has been used for centuries to promote relaxation and improve overall health. The steam helps to open up the pores in the skin, allowing for deeper cleansing and detoxification. \n\n The lime leaves used in our steam bath contain natural antioxidants that help to protect the skin from free radical damage. The Pawatta leaves have anti-inflammatory properties that help to reduce inflammation and soothe the skin. Justicia Adhatoda leaves are known for their antibacterial and antiviral properties, making them ideal for improving immunity. Kohoba leaves have analgesic properties that help to reduce pain and inflammation in the body. Cinnamon leaves help to improve blood circulation and promote relaxation. \n\n The traditional steam bath experience at Santharpana Spa is designed to provide a complete relaxation experience. You will be seated in a steam room that is heated to the perfect temperature, allowing you to sweat out toxins and impurities from your body. The steam bath helps to relax the muscles, reduce stress and tension, and promote a sense of well-being. \n\n The steam bath has several benefits, including improving circulation, promoting relaxation, reducing muscle tension and soreness, improving immunity, detoxifying the body, and reducing stress and anxiety levels. Regular steam baths can help to improve overall health and well-being. \n\n At Santharpana Spa, we take pride in providing a luxurious and relaxing experience for our guests. Our traditional steam bath is performed in a private and peaceful environment, ensuring your comfort and privacy throughout your visit. Our experienced therapists will guide you through the steam bath experience, ensuring that you get the maximum benefit from the treatment.\n\n Book your traditional steam bath experience today and experience the ultimate in relaxation and rejuvenation at Santharpana Spa.",
  },
  {
    id: 4,
    imgSrc: "images/service/service-5.jpg",
    name: " Head & Shoulder Massage",
    timeslot: "40 - 50 Minute Sessions",
    description:
      "At Santharpana Spa, we offer a relaxing and rejuvenating Head & Shoulder Massage. This massage is designed to release tension and alleviate stress from the neck, shoulders, and head, leaving you feeling relaxed and refreshed.\n\n Our Head & Shoulder Massage is a 40-50 minute session that is performed by our experienced therapists. The massage begins with a gentle touch, gradually increasing in pressure as our therapists work to release the tension in your muscles. The massage targets specific areas of the neck, shoulders, and head, using a combination of gentle strokes and pressure points to ease the stiffness and tension. \n\n This massage is ideal for those who suffer from headaches, migraines, and neck or shoulder pain. The gentle pressure and manipulation of the muscles help to improve blood flow, reduce inflammation, and alleviate pain and discomfort. \n\n Our Head & Shoulder Massage is also a great way to reduce stress and anxiety. The gentle touch and relaxation techniques used during the massage help to calm the mind and promote a sense of relaxation and well-being. \n\n At Santharpana Spa, we use only the finest quality natural oils for our Head & Shoulder Massage. Our oils are carefully chosen for their nourishing properties and are free from any harmful chemicals or additives. \n\n Book your Head & Shoulder Massage today and experience the ultimate in relaxation and rejuvenation at Santharpana Spa. Our experienced therapists will provide a personalized and luxurious massage experience, leaving you feeling relaxed and refreshed.",
  },
  {
    id: 5,
    imgSrc: "images/service/service-6.jpg",
    name: "Shirodhara",
    timeslot: "10 - 20 Minute Sessions",
    description:
      "At Santharpana Spa, we offer a unique and rejuvenating treatment known as Seerodara. Seerodara is a traditional Ayurvedic treatment that involves the use of heated herbal compresses to provide relief for tired and sore muscles.\n\n Seerodara is a 10-minute treatment that is available only until 12.00 pm, making it the perfect way to start your day. The treatment is priced at an affordable rate, making it accessible to everyone.\n\n During the Seerodara treatment, our therapists will use heated herbal compresses to massage your body. The compresses are made from a blend of natural herbs, spices, and oils, which are wrapped in a cloth and heated to the perfect temperature. The therapist will then apply the compresses to your body, using a gentle rolling and pressing motion to release tension and improve blood circulation.\n\n The Seerodara treatment is ideal for those who suffer from muscle pain, stiffness, or fatigue. The heat from the compresses helps to soothe sore muscles and provide relief from pain and discomfort. It is also a great treatment for those who are feeling stressed or anxious, as the gentle pressure and warmth help to promote relaxation and reduce tension.\n\n At Santharpana Spa, we use only the finest quality herbs, spices, and oils for our Seerodara treatment. Our herbal compresses are made from natural ingredients and are free from any harmful chemicals or additives. They are designed to provide a holistic and rejuvenating experience for your body and mind.\n\n Our experienced therapists are trained in the art of Ayurvedic massage and will ensure that you receive a personalized and luxurious Seerodara experience. They will guide you through the treatment, ensuring that you get the maximum benefit from the therapy.\n\n Book your Seerodara treatment today and experience the ultimate in relaxation and rejuvenation at Santharpana Spa. Our Seerodara treatment is a popular and affordable way to start your day, leaving you feeling refreshed and revitalized.",
  },
  {
    id: 6,
    imgSrc: "images/service/service-7.jpg",
    name: "Pinda Massage",
    timeslot: "40 - 50 Minute Sessions",
    description:
      "At Santharpana Spa, we offer a luxurious and rejuvenating Pinda massage treatment, also known as an Aromatic Pinda Massage. This treatment has its origins in both Oriental and Ayurvedic medicine, and involves the use of natural aromatic herbs, essential oils, and steam to create a truly immersive and relaxing experience.\n\n The Pinda massage is a full-body massage that uses hand-crafted bags filled with aromatic and medicinal herbs. The bags are steamed and mixed with essential oils to create a therapeutic and relaxing aroma. The herbs and oils work together to provide a range of benefits to the body, including soothing, moisturizing, and detoxifying properties..\n\n During the massage, the bags are gently pressed and rolled over the body, working to relieve tension, improve blood circulation, and release toxins from the body. The gentle heat and aroma of the herbs and oils provide a deeply relaxing and rejuvenating experience, leaving you feeling refreshed and revitalized.\n\n The Pinda massage is a 60-minute treatment that is priced at an affordable rate. Our experienced therapists are trained in the art of Ayurvedic massage and will ensure that you receive a personalized and luxurious Pinda massage experience.\n\n The Pinda massage treatment is ideal for those who suffer from muscle pain, stiffness, or fatigue. The heat from the bags and the aromatic herbs work together to soothe sore muscles and provide relief from pain and discomfort. It is also a great treatment for those who are feeling stressed or anxious, as the gentle pressure and warmth help to promote relaxation and reduce tension.\n\n At Santharpana Spa, we use only the finest quality natural ingredients for our Pinda massage treatments. Our hand-crafted bags are filled with natural herbs and essential oils that are free from any harmful chemicals or additives. They are designed to provide a holistic and rejuvenating experience for your body and mind.\n\n Book your Pinda massage treatment today and experience the ultimate in relaxation and rejuvenation at Santharpana Spa. Our Pinda massage treatment is a popular and affordable way to pamper yourself and leave you feeling refreshed and revitalized.",
  },
  {
    id: 7,
    imgSrc: "images/service/service-8.jpg",
    name: "Special Package",
    timeslot: "Stay At Our villa and Spa Treatment",
    description:
      "Welcome to Santharpana Ayurvedic Garden and Spa, your ultimate destination for a rejuvenating and relaxing vacation. We are pleased to offer you a special package for two people which includes a luxurious stay at our villa and a top-notch spa treatment.\n\n The package includes a comfortable and spacious villa that is well-equipped with all the modern amenities to make your stay as comfortable as possible. The villa is surrounded by lush green gardens, which offer a serene and peaceful atmosphere for you to unwind and recharge.\n\n Moreover, our professional therapists are dedicated to providing you with the best spa treatments available. You will be able to choose from a variety of treatments such as massage, facials, body wraps, and more. Our spa treatments are designed to help you relax, detox, and rejuvenate your mind and body.\n\n As part of this package, you will also enjoy a delicious breakfast served each morning of your stay. Our breakfast options include a range of nutritious and healthy choices to help start your day off on the right foot.\n\n We understand the importance of affordability, and we have priced this package to be accessible to everyone. For more information on pricing and to make a reservation, please email us at santharpanaspa@gmail.com.\n\n In summary, our special package for two people includes a luxurious stay at our villa, top-notch spa treatments, and a delicious breakfast, all at an affordable price. We look forward to welcoming you to Santharpana Ayurvedic Garden and Spa and providing you with a relaxing and rejuvenating experience.",
  },
];

export { servicesCard, type Services };
