/**
 * Maps a public image path to the compressed WebP twin generated by
 * `npm run optimize:images` (see scripts/optimize-images.mjs).
 *
 *   img("logo.png")               -> "/images/optimized/logo-png.webp"
 *   img("images/gallery/4.jpeg")  -> "/images/optimized/gallery/4-jpeg.webp"
 *
 * The original extension is folded into the filename rather than replaced:
 * about/img-3.jpg and about/img-3.webp are different photos, and collapsing
 * both to img-3.webp made one silently overwrite the other.
 *
 * The originals stay in public/images as the masters. If you add a new image,
 * run the script before referencing it. Must stay in sync with outputName()
 * in scripts/optimize-images.mjs.
 */
export function img(src: string): string {
  const relative = src.replace(/^\//, "").replace(/^images\//, "");
  const dot = relative.lastIndexOf(".");
  if (dot === -1) return `/images/optimized/${relative}`;

  const base = relative.slice(0, dot);
  const ext = relative.slice(dot + 1).toLowerCase();
  return `/images/optimized/${base}-${ext}.webp`;
}
